// Firebase configuration for the `signage-surgeon74` project, the same
// Firebase project the web admin app uses. Generated by hand from the
// `android/app/google-services.json` client entry for package
// `com.thesignagesurgeon.technician` (matches `applicationId` in
// `android/app/build.gradle`) — equivalent to what `flutterfire configure`
// would produce. See README "Firebase configuration" for why this file is
// committed rather than gitignored.
//
// iOS hasn't been registered in the Firebase console yet — `ios` throws
// until it is. Register an iOS app there (bundle id
// `com.thesignagesurgeon.technician` to match) and re-run
// `flutterfire configure`, or hand-add an `ios` FirebaseOptions block the
// same way `android` is built below, once you have a
// `GoogleService-Info.plist`.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — this app targets Android/iOS only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByCJZ7Ub4xd6CyLfvuXHRT00cgnVDD98Y',
    appId: '1:445858303889:android:17725af8c86bc1023fd430',
    messagingSenderId: '445858303889',
    projectId: 'signage-surgeon74',
    storageBucket: 'signage-surgeon74.firebasestorage.app',
  );

  /// A getter, not a `const`, so an iOS build fails loudly at startup
  /// instead of silently initializing Firebase with fake credentials.
  static FirebaseOptions get ios => throw UnsupportedError(
        'No iOS app is registered in the signage-surgeon74 Firebase project yet. '
        'Register one (bundle id com.thesignagesurgeon.technician), then either '
        're-run `flutterfire configure` or fill in this getter by hand from the '
        'resulting GoogleService-Info.plist — see the file header above.',
      );
}
